title   MinecrarchOS (fallback initramfs)
sort-key 02-minecrarch-fallback
linux   /arch/boot/x86_64/vmlinuz-linux-zen
initrd  /arch/boot/amd-ucode.img
initrd  /arch/boot/intel-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux-zen-fallback.img
options archisobasedir=%ARCHISO_INSTALL_DIR% archisolabel=%ARCHISO_LABEL%
